### ISSUE TITLE
Help: 如何使用反向ws

### ISSUE THREAD

**Issue by SilianZ** [whitechi73/OpenShamrock#119]
之前在 go-cqhttp 中使用了反向 Websocket 来连接机器人，在同一个设备上的。

但是现在机器人平台和QQ端不在同一个设备但在同一局域网内，不知道该如何配置。

还有，被动 Websocket 和 反向 Websocket 是一个东西吗？

我在 go-cqhttp 中的服务器是这样配置的：

```yml
servers:
  # 添加方式，同一连接方式可添加多个，具体配置说明请查看文档
  #- http: # http 通信
  #- ws:   # 正向 Websocket
  #- ws-reverse: # 反向 Websocket
  #- pprof: #性能分析服务器
  # 反向WS设置
  - ws-reverse:
      # 反向WS Universal 地址
      # 注意 设置了此项地址后下面两项将会被忽略
      universal: ws://0.0.0.0:25565/ws/
      # 重连间隔 单位毫秒
      reconnect-interval: 3000
      middlewares:
        <<: *default # 引用默认中间件
```

那么，我该如何将这些配置转移到 Shamrock 上？
